name: Generate Docker Layer

on:
  push:
    branches:
      - master
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate Docker image metadata
      id: metadata
      run: |
        if [[ ${GITHUB_REF_TYPE} == tag ]]; then
          echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        else
          echo "tag=latest" >> $GITHUB_OUTPUT
        fi

    - name: Login to GitHub registry
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ steps.metadata.outputs.tag }}
